<Project>
    <PropertyGroup>
        <!-- https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management -->
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion
            Include="Arkanis.Aspire.Hosting.Extensions.1Password"
            Version="2.1.0-dev.1" />
        <PackageVersion
            Include="Arkanis.Aspire.Hosting.Extensions.Kubernetes"
            Version="1.0.0-dev.22" />
        <PackageVersion
            Include="Arkanis.Aspire.Hosting.Extensions.Kubernetes.CloudNativePostgres"
            Version="1.0.0-dev.22" />
        <PackageVersion
            Include="Arkanis.Aspire.Hosting.Extensions.Kubernetes.ExternalSecrets"
            Version="1.0.0-dev.22" />
        <PackageVersion Include="Arkanis.Common.Hosting" Version="1.0.0-dev.1" />
        <PackageVersion Include="Aspire.Hosting.AppHost" Version="13.6.0" />
        <PackageVersion Include="Aspire.Hosting.Kubernetes" Version="13.5.4-preview.1.26464.4" />
        <PackageVersion Include="Aspire.Hosting.PostgreSQL" Version="13.6.0" />
        <PackageVersion Include="Aspire.Hosting.Redis" Version="13.6.0" />
        <PackageVersion Include="coverlet.collector" Version="10.1.0" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageVersion Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>
</Project>
