<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>Arkanis.Infra.Deployment.CitizenId.Status.AppHost.PublishTests</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector" PrivateAssets="all" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>
</Project>
